version: '3.8'
services:
  db:
    image: mysql:latest
    restart: on-failure
    container_name: plants_db
    environment:
      MYSQL_DATABASE: 'plants_db'
      MYSQL_USER: 'pratinhas'
      MYSQL_PASSWORD: 'plants'
      MYSQL_ROOT_PASSWORD: 'plants_root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
  api:
    build: .
    container_name: plants_server
    restart: on-failure
    ports: 
      - 5000:5000
    env_file:
      - .env
    networks:
      - app-network
    depends_on: #lindo
      - db

volumes:
  my-db:

networks:
  app-network:
    driver: bridge